// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_betting
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-01, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `g`, CPU: `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ../../../target/production/substrate
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_betting
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --template=../../../.maintain/frame-weight-template.hbs
// --output=../../../frame/betting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_betting.
pub trait WeightInfo {
	fn create_match_to_bet() -> Weight;
	fn bet() -> Weight;
	fn set_result() -> Weight;
	fn distribute_winnings() -> Weight;
}

/// Weights for pallet_betting using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Betting Matches (r:1 w:1)
	// Storage: Betting MatchHashes (r:1 w:1)
	fn create_match_to_bet() -> Weight {
		// Minimum execution time: 36_783 nanoseconds.
		Weight::from_ref_time(37_674_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Betting Matches (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn bet() -> Weight {
		// Minimum execution time: 75_394 nanoseconds.
		Weight::from_ref_time(77_400_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Betting Matches (r:1 w:1)
	fn set_result() -> Weight {
		// Minimum execution time: 35_553 nanoseconds.
		Weight::from_ref_time(36_196_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Betting Matches (r:1 w:1)
	fn distribute_winnings() -> Weight {
		// Minimum execution time: 19_590 nanoseconds.
		Weight::from_ref_time(20_231_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Betting Matches (r:1 w:1)
	// Storage: Betting MatchHashes (r:1 w:1)
	fn create_match_to_bet() -> Weight {
		// Minimum execution time: 36_783 nanoseconds.
		Weight::from_ref_time(37_674_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
	}
	// Storage: Betting Matches (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn bet() -> Weight {
		// Minimum execution time: 75_394 nanoseconds.
		Weight::from_ref_time(77_400_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
	}
	// Storage: Betting Matches (r:1 w:1)
	fn set_result() -> Weight {
		// Minimum execution time: 35_553 nanoseconds.
		Weight::from_ref_time(36_196_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: Betting Matches (r:1 w:1)
	fn distribute_winnings() -> Weight {
		// Minimum execution time: 19_590 nanoseconds.
		Weight::from_ref_time(20_231_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}
